version: "3.8"
services:
   backend:
     build:
       context: .
       dockerfile: Dockerfile.backend
     ports:
       - "5000:5000"
     environment:
       - NODE_ENV=production
     restart: always
 
   frontend:
     build:
       context: .
       dockerfile: Dockerfile.frontend
     ports:
       - "80:80"
     depends_on:
       - backend
     restart: always